// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Minix
{
    [Table("articoli")]
    public partial class articoli
    {
        [Key]
        public int ID { get; set; }
        [StringLength(30)]
        public string PN { get; set; }
        [StringLength(500)]
        public string DESCRIZIONE { get; set; }
        public int? SATATO { get; set; }
        [StringLength(500)]
        public string CERTIFICAZIONE { get; set; }
        public int? QTA { get; set; }
        public double? COSTO { get; set; }
        public int? ID_REPARTO { get; set; }
        public string CERTIFICATO { get; set; }
        [Column(TypeName = "date")]
        public DateTime? DATA { get; set; }

        [ForeignKey(nameof(ID_REPARTO))]
        [InverseProperty(nameof(reparto.articolis))]
        public virtual reparto ID_REPARTONavigation { get; set; }
    }
}