// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Minix
{
    [Table("reparto")]
    public partial class reparto
    {
        public reparto()
        {
            articolis = new HashSet<articoli>();
        }

        [Key]
        public int ID { get; set; }
        [StringLength(100)]
        public string DESCRIZIONE { get; set; }

        [InverseProperty(nameof(articoli.ID_REPARTONavigation))]
        public virtual ICollection<articoli> articolis { get; set; }
    }
}