// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Minix.Models
{
    public partial class user
    {
        public int id { get; set; }
        public string user1 { get; set; }
        public string password { get; set; }
    }
}